import { createContext, useContext, useState } from "react";

// ── Language map per country ──────────────────────────────────────────────────
export const COUNTRY_LANGUAGE = {
  "India":          { primary: "hi", secondary: "en", label: "हिंदी / English" },
  "Russia":         { primary: "ru", secondary: "en", label: "Русский / English" },
  "Germany":        { primary: "de", secondary: "en", label: "Deutsch / English" },
  "UAE":            { primary: "ar", secondary: "en", label: "العربية / English" },
  "United Kingdom": { primary: "en", secondary: null, label: "English" },
  "Canada":         { primary: "en", secondary: null, label: "English" },
  "USA":            { primary: "en", secondary: null, label: "English" },
};

// ── Translations ──────────────────────────────────────────────────────────────
export const TRANSLATIONS = {
  en: {
    orderNow:       "Order Now",
    exploreMenu:    "Explore Menu",
    orderOnline:    "Order Online",
    login:          "Login",
    logout:         "Logout",
    signatureTitle: "The Signature",
    signatureSub:   "Series",
    heroSub:        "Est. 2019 · Artisan Bakery",
    navCollections: "Collections",
    navAI:          "AI Customizer",
    navStory:       "Our Story",
    navReviews:     "Reviews",
    // Hero
    heroStatCustomers: "Customers",
    heroStatItems:     "Items",
    heroStatRating:    "Rating",
    heroStatYears:     "Years",
    // Collection
    collectionTitle:   "The Signature",
    collectionSub:     "Series",
    collectionAll:     "All",
    collectionBirthday:"Birthday Cake",
    collectionBirthdaySub: "Free on your big day",
    collectionDelivery:"Free Delivery",
    collectionDeliverySub: "Above ₹499 every time",
    collectionBuy5:    "Buy 5, Get 1",
    collectionBuy5Sub: "On all signature bakes",
    collectionMember:  "Member Drops",
    collectionMemberSub: "Early access to seasonal",
    collectionOrderNow:"Order Now →",
    // OrderModal
    modalTitle:        "Place Your Order",
    modalSubtitle:     "Fill in your details to continue",
    modalFullName:     "Full Name",
    modalMobile:       "Mobile",
    modalEmail:        "Email",
    modalOrderType:    "Order Type",
    modalDelivery:     "🚚 Delivery",
    modalPickup:       "🏪 Pickup",
    modalDeliveryAddr: "Delivery Address",
    modalUseLocation:  "Use Current Location",
    modalDetecting:    "Detecting...",
    modalOrSearch:     "or search",
    modalSearchPlaceholder: "Search area, street, city...",
    modalPickupNote:   "You'll pick up from our store. No delivery address needed.",
    modalSeeMenu:      "See Menu →",
    modalPoweredBy:    "Powered by OpenStreetMap · Free & no login required",
    modalEnter10Digit: "Enter 10-digit number",
    // OrderMenu
    menuOpen:          "● OPEN",
    menuSearch:        "Search cakes, pastries, brownies...",
    menuNoItems:       "No items found for",
    menuItems:         "items",
    menuItemAdded:     "item added",
    menuItemsAdded:    "items added",
    menuTotal:         "Total:",
    menuViewCart:      "View Cart →",
    menuOffersPromos:  "Offers & Promos",
    menuTapCopy:       "Tap Copy to copy the code · Apply at checkout",
    menuQuickView:     "Quick View",
    menuCustomizable:  "Customizable",
    menuCustomNote:    "This item can be customized — add a note at checkout.",
    menuAddToCart:     "Add to Cart",
    menuPiece:         "/ piece",
    menuAdd:           "ADD",
    menuYourOrder:     "Your Order",
    menuPlaceOrder:    "Place Order",
    menuPlacing:       "Placing Order...",
    menuOrderSuccess:  "✅ Order Placed Successfully!",
    menuOrderThanks:   "Thank you",
    menuWillContact:   "We'll contact you at",
    menuShortly:       "shortly.",
    menuConfirmSoon:   "You'll receive a confirmation shortly",
    menuItemTotal:     "Item total",
    menuDeliveryFee:   "Delivery fee",
    menuFree:          "FREE",
    menuEnterPromo:    "Enter promo code",
    menuRemove:        "Remove",
    menuOffers:        "🏷️ Offers",
    menuApplied:       "Applied ✓",
    menuCopied:        "Copied ✓",
    menuCopy:          "Copy",
    menuMinOrder:      "Min. order",
    menuReviews:       "reviews",
    menuFromChat:      "From Chat",
    // Footer
    footerQuickLinks:  "Quick Links",
    footerContact:     "Contact Us",
    footerOpenDaily:   "Open Daily · 8am – 9pm",
    footerRights:      "© 2026 Krishna Bakers · All rights reserved",
    footerCraft:       "Handcrafted with ❤️ for the modern palate",
    // OurStory
    storyEst:          "Est. 2019",
    storyTitle:        "Our Story",
    storySubtitle:     "Six years ago, we started with a single oven and a belief —\nthat great baking doesn't need shortcuts.",
    storyYears:        "Years",
    storyOutlets:      "Outlets",
    storyCities:       "Cities",
    storyCustomers:    "Customers",
    storyJourney:      "The Journey",
    storyPassion:      "6 Years, One Passion",
    storyPassionItalic:"One Passion",
    storyQuote:        "Every cake we bake carries six years of learning, love, and the relentless pursuit of the perfect bite.",
    storySince:        "Krishna Bakers · Since 2019",
    storyFreshTitle:   "Fresh Every Day",
    storyFreshDesc:    "Nothing pre-made. Every item baked fresh each morning.",
    storyNoShortcuts:  "No Shortcuts",
    storyNoShortcutsDesc: "Real butter, real chocolate, real fruit. No artificial flavours.",
    storyBakers:       "Trained Bakers",
    storyBakersDesc:   "Every baker completes a 3-month programme before touching an order.",
    chatWelcome:    "Hi there! 👋 Welcome to **Krishna Bakers**.\nI'm Krishna Assistant — here to help you find the perfect treat! 🎂",
    chatAskName:    "To get started, may I know your **name**? 😊",
    chatAskContact: "Could you share your **email or phone number** so we can reach you if needed?",
    chatAskType:    "Great! Now, would you like **Delivery** or **Store Pickup**? 🚚",
    chatAskAddress: "Please share your **delivery address** 📍\n(Area, Street, City)",
    chatAskCategory:"Now, what are you in the mood for today? 🍰\nPick a category or search below 👇",
    chatDelivery:   "Delivery",
    chatPickup:     "Store Pickup",
    chatPickupMsg:  "Perfect! You can pick up from our store. 🏪",
    chatDeliverTo:  "Got it! Delivering to:",
    chatMeetYou:    "Nice to meet you",
    chatReachAt:    "We'll reach you at",
    chatInvalidContact: "⚠️ That doesn't look valid.\n\nPlease enter:\n• A valid **email** — e.g. name@gmail.com\n• Or a **10-digit mobile number** — e.g. 9876543210",
    chatInvalidAddress: "⚠️ Please enter a valid delivery address (at least your area/locality).",
    chatSearchResult: "Here's what I found for",
    chatNoResult:   "Hmm, I couldn't find anything for",
    chatTryCategory:"Try picking a category below 👇",
    chatOrderQ:     "Would you like to order",
    chatOrExplore:  "Or explore more items?",
    chatOrderNow:   "🛒 Order Now",
    chatExploreMore:"🔍 Explore More",
    chatExploreBack:"Sure! Pick another category 👇",
    chatStartOver:  "Start over",
    chatWhatsApp:   "Prefer WhatsApp? Tap to chat directly →",
    chatOnline:     "● Online · Typically replies instantly",
  },
  hi: {
    orderNow:       "अभी ऑर्डर करें",
    exploreMenu:    "मेनू देखें",
    orderOnline:    "ऑनलाइन ऑर्डर",
    login:          "लॉगिन",
    logout:         "लॉगआउट",
    signatureTitle: "हमारी खास",
    signatureSub:   "बेकरी",
    heroSub:        "स्थापित 2019 · कारीगर बेकरी",
    navCollections: "संग्रह",
    navAI:          "AI कस्टमाइज़र",
    navStory:       "हमारी कहानी",
    navReviews:     "समीक्षाएं",
    // Hero
    heroStatCustomers: "ग्राहक",
    heroStatItems:     "आइटम",
    heroStatRating:    "रेटिंग",
    heroStatYears:     "साल",
    // Collection
    collectionTitle:   "हमारी खास",
    collectionSub:     "बेकरी",
    collectionAll:     "सभी",
    collectionBirthday:"जन्मदिन केक",
    collectionBirthdaySub: "आपके खास दिन पर मुफ़्त",
    collectionDelivery:"मुफ़्त डिलीवरी",
    collectionDeliverySub: "₹499 से ऊपर हर बार",
    collectionBuy5:    "5 खरीदें, 1 पाएं",
    collectionBuy5Sub: "सभी सिग्नेचर बेक्स पर",
    collectionMember:  "मेंबर ऑफर",
    collectionMemberSub: "सीज़नल आइटम पर पहली पहुँच",
    collectionOrderNow:"अभी ऑर्डर करें →",
    // OrderModal
    modalTitle:        "ऑर्डर दें",
    modalSubtitle:     "जारी रखने के लिए विवरण भरें",
    modalFullName:     "पूरा नाम",
    modalMobile:       "मोबाइल",
    modalEmail:        "ईमेल",
    modalOrderType:    "ऑर्डर प्रकार",
    modalDelivery:     "🚚 डिलीवरी",
    modalPickup:       "🏪 पिकअप",
    modalDeliveryAddr: "डिलीवरी पता",
    modalUseLocation:  "वर्तमान स्थान उपयोग करें",
    modalDetecting:    "पता लगा रहे हैं...",
    modalOrSearch:     "या खोजें",
    modalSearchPlaceholder: "क्षेत्र, सड़क, शहर खोजें...",
    modalPickupNote:   "आप हमारे स्टोर से ले सकते हैं। डिलीवरी पते की ज़रूरत नहीं।",
    modalSeeMenu:      "मेनू देखें →",
    modalPoweredBy:    "OpenStreetMap द्वारा संचालित · मुफ़्त",
    modalEnter10Digit: "10 अंकों का नंबर दर्ज करें",
    // OrderMenu
    menuOpen:          "● खुला है",
    menuSearch:        "केक, पेस्ट्री, ब्राउनी खोजें...",
    menuNoItems:       "कुछ नहीं मिला",
    menuItems:         "आइटम",
    menuItemAdded:     "आइटम जोड़ा",
    menuItemsAdded:    "आइटम जोड़े",
    menuTotal:         "कुल:",
    menuViewCart:      "कार्ट देखें →",
    menuOffersPromos:  "ऑफर और प्रोमो",
    menuTapCopy:       "कोड कॉपी करें · चेकआउट पर लगाएं",
    menuQuickView:     "त्वरित देखें",
    menuCustomizable:  "कस्टमाइज़ करें",
    menuCustomNote:    "यह आइटम कस्टमाइज़ किया जा सकता है — चेकआउट पर नोट जोड़ें।",
    menuAddToCart:     "कार्ट में जोड़ें",
    menuPiece:         "/ पीस",
    menuAdd:           "जोड़ें",
    menuYourOrder:     "आपका ऑर्डर",
    menuPlaceOrder:    "ऑर्डर दें",
    menuPlacing:       "ऑर्डर हो रहा है...",
    menuOrderSuccess:  "✅ ऑर्डर सफलतापूर्वक दिया गया!",
    menuOrderThanks:   "धन्यवाद",
    menuWillContact:   "हम आपसे संपर्क करेंगे",
    menuShortly:       "जल्द ही।",
    menuConfirmSoon:   "आपको जल्द ही पुष्टि मिलेगी",
    menuItemTotal:     "आइटम कुल",
    menuDeliveryFee:   "डिलीवरी शुल्क",
    menuFree:          "मुफ़्त",
    menuEnterPromo:    "प्रोमो कोड दर्ज करें",
    menuRemove:        "हटाएं",
    menuOffers:        "🏷️ ऑफर",
    menuApplied:       "लागू ✓",
    menuCopied:        "कॉपी हो गया ✓",
    menuCopy:          "कॉपी",
    menuMinOrder:      "न्यूनतम ऑर्डर",
    menuReviews:       "समीक्षाएं",
    menuFromChat:      "चैट से",
    // Footer
    footerQuickLinks:  "त्वरित लिंक",
    footerContact:     "संपर्क करें",
    footerOpenDaily:   "रोज़ खुला · सुबह 8 – रात 9",
    footerRights:      "© 2026 Krishna Bakers · सर्वाधिकार सुरक्षित",
    footerCraft:       "❤️ के साथ बनाया गया",
    // OurStory
    storyEst:          "स्थापित 2019",
    storyTitle:        "हमारी कहानी",
    storySubtitle:     "छह साल पहले, हमने एक ओवन और एक विश्वास के साथ शुरुआत की —\nकि अच्छी बेकिंग में कोई शॉर्टकट नहीं होता।",
    storyYears:        "साल",
    storyOutlets:      "आउटलेट",
    storyCities:       "शहर",
    storyCustomers:    "ग्राहक",
    storyJourney:      "हमारी यात्रा",
    storyPassion:      "6 साल, एक जुनून",
    storyPassionItalic:"एक जुनून",
    storyQuote:        "हर केक में छह साल की सीख, प्यार और सही बाइट की तलाश है।",
    storySince:        "Krishna Bakers · 2019 से",
    storyFreshTitle:   "रोज़ ताज़ा",
    storyFreshDesc:    "कुछ भी पहले से नहीं बनता। हर आइटम हर सुबह ताज़ा बेक होता है।",
    storyNoShortcuts:  "कोई शॉर्टकट नहीं",
    storyNoShortcutsDesc: "असली मक्खन, असली चॉकलेट, असली फल। कोई कृत्रिम स्वाद नहीं।",
    storyBakers:       "प्रशिक्षित बेकर",
    storyBakersDesc:   "हर बेकर ऑर्डर छूने से पहले 3 महीने का प्रशिक्षण पूरा करता है।",
    chatWelcome:    "नमस्ते! 👋 **Krishna Bakers** में आपका स्वागत है।\nमैं Krishna Assistant हूँ — आपकी मदद के लिए यहाँ हूँ! 🎂",
    chatAskName:    "शुरू करने के लिए, क्या आप अपना **नाम** बता सकते हैं? 😊",
    chatAskContact: "क्या आप अपना **ईमेल या फ़ोन नंबर** दे सकते हैं?",
    chatAskType:    "बढ़िया! क्या आप **डिलीवरी** चाहते हैं या **स्टोर पिकअप**? 🚚",
    chatAskAddress: "कृपया अपना **डिलीवरी पता** बताएं 📍\n(क्षेत्र, सड़क, शहर)",
    chatAskCategory:"आज आप क्या खाना चाहते हैं? 🍰\nनीचे से कैटेगरी चुनें 👇",
    chatDelivery:   "डिलीवरी",
    chatPickup:     "स्टोर पिकअप",
    chatPickupMsg:  "बढ़िया! आप हमारे स्टोर से ले सकते हैं। 🏪",
    chatDeliverTo:  "समझ गया! डिलीवरी यहाँ होगी:",
    chatMeetYou:    "आपसे मिलकर खुशी हुई",
    chatReachAt:    "हम आपसे यहाँ संपर्क करेंगे",
    chatInvalidContact: "⚠️ यह सही नहीं लग रहा।\n\nकृपया दर्ज करें:\n• एक वैध **ईमेल** — जैसे name@gmail.com\n• या **10 अंकों का मोबाइल नंबर** — जैसे 9876543210",
    chatInvalidAddress: "⚠️ कृपया एक वैध डिलीवरी पता दर्ज करें।",
    chatSearchResult: "आपकी खोज का परिणाम",
    chatNoResult:   "माफ़ करें, कुछ नहीं मिला",
    chatTryCategory:"नीचे से कैटेगरी चुनें 👇",
    chatOrderQ:     "क्या आप ऑर्डर करना चाहते हैं",
    chatOrExplore:  "या और आइटम देखें?",
    chatOrderNow:   "🛒 अभी ऑर्डर करें",
    chatExploreMore:"🔍 और देखें",
    chatExploreBack:"ज़रूर! दूसरी कैटेगरी चुनें 👇",
    chatStartOver:  "फिर से शुरू करें",
    chatWhatsApp:   "WhatsApp पर बात करें →",
    chatOnline:     "● ऑनलाइन · तुरंत जवाब देते हैं",
  },
  ru: {
    orderNow:       "Заказать",
    exploreMenu:    "Меню",
    orderOnline:    "Заказ онлайн",
    login:          "Войти",
    logout:         "Выйти",
    signatureTitle: "Фирменная",
    signatureSub:   "Коллекция",
    heroSub:        "Осн. 2019 · Авторская пекарня",
    navCollections: "Коллекции",
    navAI:          "AI Кастомайзер",
    navStory:       "О нас",
    navReviews:     "Отзывы",
    chatWelcome:    "Привет! 👋 Добро пожаловать в **Krishna Bakers**.\nЯ Krishna Assistant — помогу выбрать лучшее! 🎂",
    chatAskName:    "Для начала, как вас зовут? 😊",
    chatAskContact: "Поделитесь вашим **email или номером телефона**?",
    chatAskType:    "Отлично! **Доставка** или **самовывоз**? 🚚",
    chatAskAddress: "Укажите ваш **адрес доставки** 📍\n(Район, улица, город)",
    chatAskCategory:"Что вы хотите сегодня? 🍰\nВыберите категорию 👇",
    chatDelivery:   "Доставка",
    chatPickup:     "Самовывоз",
    chatPickupMsg:  "Отлично! Вы можете забрать заказ в нашем магазине. 🏪",
    chatDeliverTo:  "Понял! Доставим по адресу:",
    chatMeetYou:    "Приятно познакомиться",
    chatReachAt:    "Свяжемся с вами по",
    chatInvalidContact: "⚠️ Неверный формат.\n\nВведите:\n• Действительный **email** — напр. name@gmail.com\n• Или **номер телефона**",
    chatInvalidAddress: "⚠️ Пожалуйста, введите корректный адрес доставки.",
    chatSearchResult: "Результаты поиска для",
    chatNoResult:   "Ничего не найдено для",
    chatTryCategory:"Выберите категорию 👇",
    chatOrderQ:     "Хотите заказать",
    chatOrExplore:  "Или посмотреть другие товары?",
    chatOrderNow:   "🛒 Заказать",
    chatExploreMore:"🔍 Смотреть ещё",
    chatExploreBack:"Конечно! Выберите другую категорию 👇",
    chatStartOver:  "Начать заново",
    chatWhatsApp:   "Написать в WhatsApp →",
    chatOnline:     "● Онлайн · Отвечаем мгновенно",
  },
  de: {
    orderNow:       "Jetzt bestellen",
    exploreMenu:    "Menü erkunden",
    orderOnline:    "Online bestellen",
    login:          "Anmelden",
    logout:         "Abmelden",
    signatureTitle: "Die Signature",
    signatureSub:   "Kollektion",
    heroSub:        "Gegr. 2019 · Handwerksbäckerei",
    navCollections: "Kollektionen",
    navAI:          "KI-Anpasser",
    navStory:       "Unsere Geschichte",
    navReviews:     "Bewertungen",
    chatWelcome:    "Hallo! 👋 Willkommen bei **Krishna Bakers**.\nIch bin Krishna Assistant — hier um zu helfen! 🎂",
    chatAskName:    "Wie ist Ihr **Name**? 😊",
    chatAskContact: "Bitte teilen Sie Ihre **E-Mail oder Telefonnummer**?",
    chatAskType:    "Super! **Lieferung** oder **Abholung**? 🚚",
    chatAskAddress: "Bitte geben Sie Ihre **Lieferadresse** an 📍\n(Straße, Stadt)",
    chatAskCategory:"Was möchten Sie heute? 🍰\nWählen Sie eine Kategorie 👇",
    chatDelivery:   "Lieferung",
    chatPickup:     "Abholung",
    chatPickupMsg:  "Super! Sie können in unserem Geschäft abholen. 🏪",
    chatDeliverTo:  "Verstanden! Lieferung an:",
    chatMeetYou:    "Schön, Sie kennenzulernen",
    chatReachAt:    "Wir erreichen Sie unter",
    chatInvalidContact: "⚠️ Das sieht nicht gültig aus.\n\nBitte eingeben:\n• Eine gültige **E-Mail** — z.B. name@gmail.com\n• Oder eine **Telefonnummer**",
    chatInvalidAddress: "⚠️ Bitte geben Sie eine gültige Lieferadresse ein.",
    chatSearchResult: "Suchergebnisse für",
    chatNoResult:   "Nichts gefunden für",
    chatTryCategory:"Wählen Sie eine Kategorie 👇",
    chatOrderQ:     "Möchten Sie bestellen",
    chatOrExplore:  "Oder weitere Artikel erkunden?",
    chatOrderNow:   "🛒 Bestellen",
    chatExploreMore:"🔍 Mehr erkunden",
    chatExploreBack:"Natürlich! Wählen Sie eine andere Kategorie 👇",
    chatStartOver:  "Neu starten",
    chatWhatsApp:   "Lieber WhatsApp? Hier tippen →",
    chatOnline:     "● Online · Antwortet sofort",
  },
  ar: {
    orderNow:       "اطلب الآن",
    exploreMenu:    "استكشف القائمة",
    orderOnline:    "اطلب أونلاين",
    login:          "تسجيل الدخول",
    logout:         "تسجيل الخروج",
    signatureTitle: "المجموعة",
    signatureSub:   "المميزة",
    heroSub:        "تأسست 2019 · مخبز حرفي",
    navCollections: "المجموعات",
    navAI:          "مخصص AI",
    navStory:       "قصتنا",
    navReviews:     "التقييمات",
    chatWelcome:    "مرحباً! 👋 أهلاً بك في **Krishna Bakers**.\nأنا Krishna Assistant — هنا لمساعدتك! 🎂",
    chatAskName:    "للبدء، ما **اسمك**؟ 😊",
    chatAskContact: "هل يمكنك مشاركة **بريدك الإلكتروني أو رقم هاتفك**؟",
    chatAskType:    "رائع! **توصيل** أم **استلام من المتجر**؟ 🚚",
    chatAskAddress: "يرجى مشاركة **عنوان التوصيل** 📍\n(المنطقة، الشارع، المدينة)",
    chatAskCategory:"ماذا تريد اليوم؟ 🍰\nاختر فئة 👇",
    chatDelivery:   "توصيل",
    chatPickup:     "استلام من المتجر",
    chatPickupMsg:  "رائع! يمكنك الاستلام من متجرنا. 🏪",
    chatDeliverTo:  "فهمت! التوصيل إلى:",
    chatMeetYou:    "سعيد بلقائك",
    chatReachAt:    "سنتواصل معك على",
    chatInvalidContact: "⚠️ هذا لا يبدو صحيحاً.\n\nيرجى إدخال:\n• **بريد إلكتروني** صحيح\n• أو **رقم هاتف** صحيح",
    chatInvalidAddress: "⚠️ يرجى إدخال عنوان توصيل صحيح.",
    chatSearchResult: "نتائج البحث عن",
    chatNoResult:   "لم يتم العثور على شيء لـ",
    chatTryCategory:"اختر فئة 👇",
    chatOrderQ:     "هل تريد طلب",
    chatOrExplore:  "أو استكشاف المزيد؟",
    chatOrderNow:   "🛒 اطلب الآن",
    chatExploreMore:"🔍 استكشف المزيد",
    chatExploreBack:"بالتأكيد! اختر فئة أخرى 👇",
    chatStartOver:  "ابدأ من جديد",
    chatWhatsApp:   "تفضل واتساب؟ اضغط هنا →",
    chatOnline:     "● متصل · يرد فوراً",
  },
};

// ── Location hierarchy ────────────────────────────────────────────────────────
export const LOCATIONS = [
  {
    country: "India", flag: "🇮🇳",
    states: [
      {
        state: "Delhi NCR",
        cities: [
          { city: "North Delhi", areas: ["Civil Lines", "Model Town", "Rohini", "Pitampura"], type: "nearby" },
          { city: "South Delhi", areas: ["Hauz Khas", "Saket", "Vasant Kunj", "Greater Kailash"], type: "nearby" },
          { city: "East Delhi", areas: ["Laxmi Nagar", "Preet Vihar", "Mayur Vihar", "Patparganj"], type: "nearby" },
          { city: "West Delhi", areas: ["Rajouri Garden", "Janakpuri", "Dwarka", "Uttam Nagar"], type: "nearby" },
          { city: "Noida", areas: ["Sector 18", "Sector 62", "Sector 137", "Greater Noida"], type: "nearby" },
          { city: "Gurgaon", areas: ["DLF Phase 1", "Cyber City", "Sohna Road", "Golf Course Road"], type: "nearby" },
        ],
      },
      {
        state: "Maharashtra",
        cities: [
          { city: "Mumbai", areas: ["Bandra", "Andheri", "Juhu", "Colaba"], type: "semi" },
          { city: "Pune", areas: ["Koregaon Park", "Viman Nagar", "Hinjewadi", "Kothrud"], type: "semi" },
          { city: "Nashik", areas: ["College Road", "Gangapur Road"], type: "semi" },
        ],
      },
      {
        state: "Uttar Pradesh",
        cities: [
          { city: "Lucknow", areas: ["Hazratganj", "Gomti Nagar", "Aliganj"], type: "semi" },
          { city: "Agra", areas: ["Taj Ganj", "Sikandra"], type: "semi" },
          { city: "Varanasi", areas: ["Lanka", "Sigra"], type: "far" },
        ],
      },
      {
        state: "Rajasthan",
        cities: [
          { city: "Jaipur",   areas: ["C-Scheme", "Vaishali Nagar", "Malviya Nagar"], type: "semi" },
          { city: "Udaipur",  areas: ["City Palace Road", "Fateh Sagar"],             type: "far"  },
          { city: "Jodhpur",  areas: ["Sardarpura", "Paota"],                         type: "far"  },
        ],
      },
      {
        state: "Goa",
        cities: [
          { city: "Panaji",   areas: ["Fontainhas", "Miramar", "Dona Paula"],         type: "far"  },
          { city: "Margao",   areas: ["Monte Hill", "Fatorda"],                       type: "far"  },
          { city: "Calangute",areas: ["Baga", "Anjuna", "Candolim"],                  type: "far"  },
        ],
      },
      {
        state: "Karnataka",
        cities: [
          { city: "Bangalore",areas: ["Koramangala", "Indiranagar", "Whitefield", "HSR Layout"], type: "semi" },
          { city: "Mysore",   areas: ["Vijayanagar", "Gokulam"],                      type: "far"  },
        ],
      },
      {
        state: "Tamil Nadu",
        cities: [
          { city: "Chennai",  areas: ["Anna Nagar", "T Nagar", "Adyar", "Velachery"], type: "semi" },
          { city: "Coimbatore",areas: ["RS Puram", "Gandhipuram"],                    type: "far"  },
        ],
      },
    ],
  },
  {
    country: "United Kingdom", flag: "🇬🇧",
    states: [
      {
        state: "England",
        cities: [
          { city: "London", areas: ["Southall", "Wembley", "Tooting", "Brick Lane"], type: "international" },
          { city: "Birmingham", areas: ["Handsworth", "Sparkhill", "Edgbaston"], type: "international" },
          { city: "Manchester", areas: ["Rusholme", "Longsight", "Didsbury"], type: "international" },
          { city: "Leicester", areas: ["Belgrave Road", "Highfields"], type: "international" },
        ],
      },
    ],
  },
  {
    country: "UAE", flag: "🇦🇪",
    states: [
      {
        state: "Dubai",
        cities: [
          { city: "Dubai", areas: ["Bur Dubai", "Deira", "JBR", "Downtown Dubai"], type: "international" },
          { city: "Abu Dhabi", areas: ["Khalidiyah", "Corniche", "Al Reem Island"], type: "international" },
          { city: "Sharjah", areas: ["Al Nahda", "Rolla Square"], type: "international" },
        ],
      },
    ],
  },
  {
    country: "Canada", flag: "🇨🇦",
    states: [
      {
        state: "Ontario",
        cities: [
          { city: "Toronto", areas: ["Brampton", "Mississauga", "Scarborough"], type: "international" },
          { city: "Ottawa", areas: ["Kanata", "Nepean"], type: "international" },
        ],
      },
    ],
  },
  {
    country: "USA", flag: "🇺🇸",
    states: [
      {
        state: "New York",
        cities: [
          { city: "New York City", areas: ["Jackson Heights", "Flushing", "Edison NJ"], type: "international" },
        ],
      },
      {
        state: "California",
        cities: [
          { city: "San Francisco", areas: ["Fremont", "Sunnyvale", "Milpitas"], type: "international" },
        ],
      },
    ],
  },
  {
    country: "Russia", flag: "🇷🇺",
    states: [
      {
        state: "Moscow Oblast",
        cities: [
          { city: "Moscow",          areas: ["Arbat", "Tverskoy", "Zamoskvorechye", "Sokolniki"], type: "international" },
          { city: "Saint Petersburg",areas: ["Nevsky", "Vasileostrovsky", "Petrogradsky"],        type: "international" },
        ],
      },
      {
        state: "Tatarstan",
        cities: [
          { city: "Kazan",           areas: ["Old Tatar Sloboda", "Kremlin District"],             type: "international" },
        ],
      },
    ],
  },
  {
    country: "Germany", flag: "🇩🇪",
    states: [
      {
        state: "Bavaria",
        cities: [
          { city: "Munich",          areas: ["Maxvorstadt", "Schwabing", "Neuhausen", "Glockenbachviertel"], type: "international" },
          { city: "Nuremberg",       areas: ["Altstadt", "Gostenhof"],                            type: "international" },
        ],
      },
      {
        state: "Berlin",
        cities: [
          { city: "Berlin",          areas: ["Mitte", "Prenzlauer Berg", "Kreuzberg", "Charlottenburg"], type: "international" },
        ],
      },
      {
        state: "Hamburg",
        cities: [
          { city: "Hamburg",         areas: ["Altona", "Eimsbüttel", "HafenCity"],                type: "international" },
        ],
      },
    ],
  },
];

// ── Product type by location ──────────────────────────────────────────────────
export const LOCATION_PRODUCT_MAP = {
  nearby: {
    label: "Fresh Baked",
    badge: "🟢 Fresh",
    desc: "Delivered within 2-4 hours",
    deliveryTime: "2-4 hrs",
    canDeliver: ["Signature Cakes","Luxe Collection","Viennoiserie","Cupcakes","Donuts","Brownies","Tea Cakes","Cookies","Breads","International"],
    cannotDeliver: [],
    note: "All fresh items available. Same-day delivery guaranteed.",
    categories: ["Signature Cakes","Viennoiserie","Cupcakes","Donuts","Brownies","Tea Cakes","Cookies","Breads","Luxe Collection","International"],
  },
  semi: {
    label: "Same Day",
    badge: "🟡 Same Day",
    desc: "Delivered within 6-8 hours",
    deliveryTime: "6-8 hrs",
    canDeliver: ["Signature Cakes","Luxe Collection","Cookies","Brownies","Breads","Tea Cakes","International"],
    cannotDeliver: ["Viennoiserie","Cupcakes","Donuts"],
    note: "Cream-based & delicate items not available. Sturdy bakes only.",
    categories: ["Signature Cakes","Luxe Collection","Cookies","Brownies","Breads","Tea Cakes","International"],
  },
  far: {
    label: "Travel Safe",
    badge: "🟠 Packaged",
    desc: "Packaged for long distance",
    deliveryTime: "1-2 days",
    canDeliver: ["Cookies","Brownies","Breads","Luxe Collection","International"],
    cannotDeliver: ["Signature Cakes","Viennoiserie","Cupcakes","Donuts","Tea Cakes"],
    note: "Only dry & vacuum-packed items. No fresh cream or mousse cakes.",
    categories: ["Cookies","Brownies","Breads","International","Luxe Collection"],
  },
  international: {
    label: "Export Ready",
    badge: "✈️ Export",
    desc: "Vacuum sealed, 7-day shelf life",
    deliveryTime: "5-7 days",
    canDeliver: ["Cookies","Brownies","Luxe Collection","International"],
    cannotDeliver: ["Signature Cakes","Viennoiserie","Cupcakes","Donuts","Tea Cakes","Breads"],
    note: "Only export-grade vacuum sealed items. Customs compliant packaging.",
    categories: ["Cookies","Brownies","Luxe Collection","International"],
  },
};

// ── Context ───────────────────────────────────────────────────────────────────
const LocationContext = createContext(null);

export function LocationProvider({ children }) {
  const [location, setLocation] = useState({
    country: "India",
    flag: "🇮🇳",
    state: "Delhi NCR",
    city: "South Delhi",
    area: "Hauz Khas",
    type: "nearby",
  });

  const [lang, setLang] = useState("en"); // always English by default

  function setLocationWithLang(loc) {
    setLocation(loc);
    setLang("en"); // reset to English on every location change
  }

  return (
    <LocationContext.Provider value={{ location, setLocation: setLocationWithLang, lang, setLang }}>
      {children}
    </LocationContext.Provider>
  );
}

export function useLocation() {
  return useContext(LocationContext);
}
